version: "3.8"

services:
  db:
    image: postgres:16
    container_name: postgresql_projeto_cotacoes
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
